### ISSUE TITLE
What is label '255'?

### ISSUE THREAD

**Issue by hoonkai** [alicranck/coco2voc#3]
Hi

First of all, great work there!

I just wanted to ask about labels in class segmentation PNGs. I've noticed that quite a few of them contain the label `255` and not sure what that's supposed to represent. Because COCO has just 80 classes, what's label `255` meant to represent? There are heaps of `0`s, which I presume represent pixels to ignore.

Thanks in advance.

**Comment by alicranck** [comment]
Hi @hoonkai, it seems like it might be a problem with saving the images. I'll try and take a look over the next few days. Thanks for pointing it out to me!

**Comment by hoonkai** [comment]
Hi @alicranck I should have noted that it's all sorted now. Thanks!

**Comment by alicranck** [comment]
Great! 
If you want to PR your fix or let me know what was the problem I'll be happy to hear
