### ISSUE TITLE
Bug in converting instance masks

### ISSUE THREAD

**Issue by theodoruszq** [alicranck/coco2voc#6]
https://github.com/alicranck/coco2voc/blob/deec88cb34c7f09227ed79f0bfa5f3eb02bedc6b/coco2voc_aux.py#L25

This should be:
```
    for i,mask in enumerate(masks, 1):
        instance_seg = np.where(instance_seg>0, instance_seg, mask*i)
```

Example img id: 329486. Using your code, the train is just disappeared. I only check the instance situtation and I am not aware of the other masks or ids.

Thanks for your code anyway.

**Comment by alicranck** [comment]
Hey @sydney0zq ,

You're right,  it seems there is a bug that causes the first mask to be ignored. 
However, your fix would break the class and id segmentations. I suggest to fix in the following way:

    for i,mask in enumerate(masks):
        instance_seg = np.where(instance_seg>0, instance_seg, mask*(i+1))

If you have time to test and see that it is working properly it will be much appreciated.

Thanks.

**Comment by theodoruszq** [comment]
Hi @alicranck , 

Yes, this is equal to the modification on the `enumerate` iterator. It works properly in this style. In my task, I only need the instance mask, so that I modify it in a hard-code way.

Thanks for your quick reply.
