### ISSUE TITLE
Saving Images with Matplotlib Leading to an Extra Channel

### ISSUE THREAD

**Issue by ElectronicElephant** [alicranck/coco2voc#7]
Similar to this [stackoverflow](https://stackoverflow.com/questions/52803336/matplotlib-changes-channels-of-image-when-saving) link, saving images with Matplotlib will add one extra channel to the file(i.e., 4 channels in total), which is not necessary and may cause problems.

Standard VOC dataset format allows only one channel. So I made some changs to ~ Line 50 in coco2voc.py

`        class_seg, instance_seg, id_seg = annsToSeg(anns, coco_instance)
       # class_seg = np.dstack([class_seg] * 3).astype(np.uint8)  # Stack to create an RGB image BUT NO NEED
        # print("class seg", class_seg.shape)`
        # print("instance seg", instance_seg.shape)
        # plt.imsave(os.path.join(class_target_path, str(img) + '.png'), class_seg)
        Image.fromarray(class_seg).convert("L").save(class_target_path + '/' + str(img) + '.png')
        # plt.imsave(os.path.join(instance_target_path, str(img) + '.png'), instance_seg, cmap=plt.get_cmap('inferno'))
        Image.fromarray(instance_seg).convert("L").save(instance_target_path + '/' + str(img) + '.png')`

Saving files with PIL increases speed by around 30%. On my i7-8750H notebook with NVMe SSDs, it took me about 2 hours to change the whole coco train2017 to voc format.

**Comment by alicranck** [comment]
Hi @EletronicElephant ,

Thanks for pointing it out! I'll take a look at it soon. If you want, you're welcome to send a PR.

**Comment by ElectronicElephant** [comment]
Hi @alicranck ,

Sorry I'm trying but I'm still a green hand to GitHub. Fortunately, the idea is not that complex - just two or three lines of  code. -:)

**Comment by alicranck** [comment]
Thanks @EletronicElephant ! I've updated the code with your recommendations, and added a loading example to example.py

**Comment by ElectronicElephant** [comment]
@alicranck That's great. Thank you for your efforts!
