### ISSUE TITLE
Just wondering how you treat overlapped instances?

### ISSUE THREAD

**Issue by ElectronicElephant** [alicranck/coco2voc#8]
Hello, I'm still new to the coco dataset and I'm wondering how you treat the possible overlapped instances? Does coco gurantee that there's no overlap between instances?

Thank you!

**Comment by alicranck** [comment]
Hi @EletronicElephant , 
Neither the dataset nor my code guarantee anything about overlapping instances. That being said, I found that in all cases overlap between masks, it is a mask of a smaller object that is contained in the mask of a larger object (a plate on a table for example). To address this problem I sort the masks by size and make sure that the smaller masks are on top. Still, while I haven't encountered it, there could be cases where masks partially overlap and so, as I said - I can't guarantee that no information is lost.

**Comment by ElectronicElephant** [comment]
> Hi @EletronicElephant ,
> Neither the dataset nor my code guarantee anything about overlapping instances. That being said, I found that in all cases overlap between masks, it is a mask of a smaller object that is contained in the mask of a larger object (a plate on a table for example). To address this problem I sort the masks by size and make sure that the smaller masks are on top. Still, while I haven't encountered it, there could be cases where masks partially overlap and so, as I said - I can't guarantee that no information is lost.

Thank you. This solves my confusion. I think I'd better do with the COCO RLE annotations directly instead of converting them first into VOC format to avoid possible broken masks.
