### ISSUE TITLE
What is labels_target_folder?

### ISSUE THREAD

**Issue by buseyaren** [alicranck/coco2voc#9]
if __name__ == '__main__':
    # !!Change paths to your local machine!!
    annotations_file = '/home/dl/1TB-Volumn/MSCOCO2017/annotations/instances_train2017.json'
    **labels_target_folder = '/home/dl/PycharmProjects/coco2voc-master/output'**
    data_folder = '/home/dl/1TB-Volumn/MSCOCO2017/train2017'

**Comment by alicranck** [comment]
hi @BuseYarenTekin,
This is where the output is going to be saved.
